TOMToolkit/tom_base

- tom_setup/management/commands/tom_setup.py
- tom_setup/templates/tom_setup/settings.tmpl
This commit makes sure that the setup script creates a top level
`static` directory and adds the appropriate `STATICFILES_DIRS` setting
so that users can place static files here immediately without needing to
start an app (as suggested in the django docs). This commit will be
accompanied by the appropriate documentation updates.
Fixes https://github.com/TOMToolkit/tom_base/issues/42
> Provide default root static directory

- tom_base/settings.py
- tom_common/hooks.py
- tom_observations/admin.py
- tom_observations/models.py
- tom_setup/templates/tom_setup/settings.tmpl
- tom_targets/models.py
Adds support for providing arbitrary code hooks to certain actions
within the TOM toolkit. The goal of this is to make it easy for TOM
authors to run custom scripts without needing to change the TOM
internals.
Documentation: https://tomtoolkit.github.io/docs/custom_code
Fixes https://github.com/TOMToolkit/tom_base/issues/46
> Add support for external code hooks

- tom_base/settings.py
- tom_common/exceptions.py
- tom_common/middleware.py
- tom_observations/facilities/lco.py
- tom_observations/views.py
- tom_setup/templates/tom_setup/settings.tmpl
This commit adds a middleware which catches a custom exception
`ImproperCredentialsException` which should be raised by modules when
there is an authentication problem. If left uncaught, this exception
will be handled by the custom middleware which will redirect the user to
the homepage and display an error.
Fixes https://github.com/TOMToolkit/tom_base/issues/38
> Handle external auth problems

- tom_base/settings.py
- tom_common/middleware.py
- tom_common/tests.py
- tom_setup/templates/tom_setup/settings.tmpl
This commit allows configuring the authentication strategy for the
entire TOM. Currently there are 2 values: READ_ONLY and LOCKED, the
latter which will require authentication to access any view (besides
login and a configurable list of exceptions).
> Add configurable auth strategy

- tom_common/templatetags/tom_common_extras.py
- tom_targets/forms.py
- tom_targets/templates/tom_targets/partials/target_data.html
- tom_targets/templatetags/targets_extras.py
- tom_targets/tests/tests.py
This commit allows users to input ra/dec as sexigesimal when creating a
target, as well as displaying both deg and sexigesimal respresentaions
of ra/dec on the target detail page.
>  Add support for sexigesimal 

- tom_alerts/templates/tom_alerts/query_result.html
- tom_alerts/tests/tests_generic.py
- tom_alerts/views.py
- tom_dataproducts/models.py
- tom_dataproducts/views.py
Fixes crash when submitting multiselect forms with no selections in dataproducts and alerts
Adds saner redirection when creating a target from a single alert
Fixes #22
> Closes the loop on issue #22

- tom_alerts/brokers/mars.py
A filter in the MARS moduke was incorrectly named resuling in it not
working at all.
> Rename incorrect time_since MARS filter. Fixes #98

- tom_alerts/brokers/scout.py
Removed lines causing extra data from scout broker to be imported as target extra fields.
> Prevent scout broker from passing extra data into tags

- tom_targets/views.py
Previous fix was wrong. It only counted the number of targets displayed in the list, which maxes out at 25 a page. Now corrected.
> Fix update num targets

- tom_dataproducts/templates/tom_dataproducts/dataproduct_list.html
Presently long names for data products cause the table at `/dataproducts/data/` to overlap the filters and list of data product groups:
This patch truncates names after 40 characters:
> Truncate long names in the /dataproducts/data/ view to avoid overlapping

- tom_targets/templatetags/targets_extras.py
As of Plotly 4.0.0, land masses are shown by default on geo plots. While we should consider pinning the version, this will correct the issue for anyone currently on the new Plotly version.
> Added plotly attribute to account for 4.0.0 update

- tom_targets/models.py
- tom_targets/tests/tests.py
Previously the `extra_fields` dictionary for the `Target` model had all
values as strings. E.g. `'False'` (as a string) instead of `False` for a
boolean field. This commit makes sure the types are correct.
(Note: The only place this dictionary was used in the `tom_base` code is
in the target detail template. The template still displays properly
after this change.)
> Make extra field values in Target.extra_fields the correct type

- tom_alerts/brokers/antares.py
- tom_setup/templates/tom_setup/settings.tmpl
- tom_targets/templates/tom_targets/target_list.html
At present, if a target is created without an identifier (either programmatically or via CSV import), it is not selectable in the target list view, as the identifier is the link to the detail page. Additionally, when updating reduced data from brokers, the update fails with a somewhat nonsensical error message if the BROKER_CREDENTIALS are not present in settings.py
This change adds a placeholder for targets without identifiers in the list view, adds an empty BROKER_CREDENTIALS in settings.tmpl, and accesses the antares credentials in such a way as to raise the associated ImproperlyConfigured error.
> Added placeholder identifier for targets without one on target list page

- tom_dataproducts/models.py
- tom_dataproducts/tests/tests.py
- tom_observations/templatetags/observation_extras.py
At present, thumbnails cannot be generated for raw images, only for LCO-reduced images. This PR does the following:
- Changes the header used to identify valid images to `EXTNAME` instead of `XTENSION`, which appears to be a BANZAI-generated header keyword.
- Uses magic to validate filetype instead of relying solely on astropy's fits library, which we do elsewhere.
It also addresses the Plotly update separating the properties for coastline and landmass appearances for the observation distribution plot.
> Changed extension header for identifying valid fits files

- tom_dataproducts/models.py
This method returns the URL for a thumbnail preview of a FITS file, and
would previously raise an exception when called on a non-FITS file. This
commit makes an empty string be returned in such cases, which avoids the
need to check filetype before calling from templates etc.
> Make sure DataProduct.get_preview() does not error when a thumbnail cannot be drawn

- tom_targets/forms.py
Change the widget for extra fields of type 'string' to a `<textarea>` instead of the default text input.
This makes it possible to use extra fields for long-form text data, and for the text to include newlines.
For example, the new asteroid tracker application uses extra fields in the TOM to store detailed information about a target in markdown, which is too long to reasonably edit in a normal textbox. It is anticipated that other projects could also benefit from storing long-form text in extra fields.
Existing functionality is not affected, and the other text inputs on the form remain the same.
> Use a textarea for string extra fields in target create/update form

- tom_observations/facilities/lco.py
- tom_observations/facilities/soar.py
At present, any facility inheriting from LCO will return LCO's sites. This PR corrects that issue.
This will also be a problem for any of the other properties that live in the module rather than the facility, but we can address that as and when needed.
> Moved sites into facility class to make inheritance more streamlined

- tom_common/tests.py
- tom_targets/templates/tom_targets/target_form.html
- tom_targets/templates/tom_targets/target_list.html
Very quickly addressing Andy's concern about ambiguity in target creation. This consolidates the three methods of target creation (manual, import, and catalog search) into one button/dropdown.
> Consolidated target creation

- tom_targets/filters.py
- tom_targets/templates/tom_targets/target_list.html
Fixes two small problems I noticed after updating SNEx 2 to tomtoolkit 1.0:
If a search string is in multiple names for a single target (e.g. '17cbv' is in both 'AT 2017cbv' and 'SN 2017cbv'), searching would return the same target multiple times.
Removed duplicated column in targets table.
> Quick fixes so main target table displays correctly

- setup.py
> Install dataclasses if python < 3.7

- tom_observations/tests/tests.py
- tom_targets/templates/tom_targets/partials/aladin.html
Addresses [issue 198](https://github.com/TOMToolkit/tom_base/issues/198) by adding a marker at the target position on the Aladin maps that get generated for each target detail page. This lets users see where exactly the target is even if you pan around the map.
> Adding marker at target position on Aladin map

- tom_observations/templates/tom_observations/observation_form.html
Small fix to the observation form template. The template has multiple tabs (one for each observation type), and this correctly registers the default (first) tab as the active one. Just a minor aesthetic fix.
Tested on facilities with one and multiple observations types.
> Minor fix so default observation form is active tab

- tom_dataproducts/models.py
This allows easy access to the latest photometry point or spectrum of a target on the command line by using `target.reduceddatum_set.latest`, which is useful, for example, for displaying how bright a target currently is. Currently, running this command raises `ValueError: earliest() and latest() require either fields as positional arguments or 'get_latest_by' in the model's Meta.`
> get earliest/latest ReducedDatum by timestamp

- docs/customization/target_fields.md
- tom_base/settings.py
- tom_targets/models.py
Simple change that allows a user to specify a default value for an extra_field, as requested in #227.
> Added ability to specific default values of extra fields

- setup.py
When upgraded to Django 3 with django-contrib-comments < 1.9.2, the TOM Toolkit fails to start. To facilitate upgrading to Django 3, I've added a requirement of at least 1.9.2 for django-contrib-comments.
Additionally, Django 2.2 was identified as the minimum version due to the use of django.db.functions.math.
> modify setup.py to allow support for Django 3

- tom_common/templates/tom_common/base.html
Will be "First Last (username)" or "username" if no First Last.
(if either First _or_ Last are present they'll be shown with the
username in parens).
I'm 'PR'ing into development so you can manage when you want to pull this in.
> fix username in base navbar

- tom_targets/templates/tom_targets/partials/target_data.html
- tom_targets/templatetags/targets_extras.py
Etienne pointed out in #240 that `TargetExtras` will not be displayed on `Targets` that don't have them. While this was originally by design, it seems like if a field is ubiquitous enough to be added to `settings.EXTRA_FIELDS`, it should probably appear on every target, value or not. The template can be overridden if this isn't desirable behavior.
I've discussed this with @rachel3834 and she concurs.
> Updated templatetag to display extras regardless of value

- tom_alerts/brokers/tns.py
- tom_catalogs/harvesters/tns.py
The Transient Name Server recently migrated their server to AWS, and now they have a new URL. See https://www.wis-tns.org/content/tns-newsfeed#comment-wrapper-20280 for more details.
I updated all instances of the wis-tns.weizmann.ac.il URL to www.wis-tns.org throughout the package.
> update TNS URL

- tom_alerts/alerts.py
- tom_alerts/brokers/fink.py
- tom_setup/templates/tom_setup/settings.tmpl
This PR follows issue #440 by adding a default button for the Fink broker. After a fresh installation of `tom_base`, I have a new button `Fink` in the broker list, that shows:
> Add default button for the Fink broker

- tom_alerts/brokers/tns.py
Ofer Yaron, one of the TNS developers, reports by email that the old URL (www.wis-tns.org) is no longer being redirected, so I have updated the TNS_BASE_URL parameter.
> Updated TNS URL

- tom_targets/templates/tom_targets/partials/target_table.html
- tom_targets/templates/tom_targets/target_list.html
- tom_targets/templatetags/targets_extras.py
It would be helpful to have the target list as it's own template so that
we can override it without overriding the entire page. A good example
would be adding columns to display in the table, while still being able
to get updates from upstream on the rest of the page.
> Seperate Target list table into a partial

- docs/common/customsettings.rst
- tom_base/settings.py
- tom_common/templates/tom_common/base.html
- tom_common/templatetags/tom_common_extras.py
- tom_setup/templates/tom_setup/settings.tmpl
It would be nice if users would not have to override
tom_common/base.html just to update the name of the TOM that is
displayed in the header and title of each page. I think those templates
are just fine.
This introduces a backwards compatible tag that pulls a TOM_NAME setting
from settings.py but defaults to "TOM Toolkit" in case that setting
doesn't exist. I added the setting to the setup template, but it might
be a good candidate to add to the setup script as an interactive
question as well.
> Make TOM name configurable

- tom_targets/groups.py
- tom_targets/templates/tom_targets/target_list.html
- tom_targets/tests/tests.py
- tom_targets/views.py
This PR adds functions for moving targets between TargetLists. If a
target is moved to a TargetList, it's previous lists are cleared and
the target is added to the specified TargetList. If the target already
exists in the specified TargetList a warning is displayed but the
target's previous associations are not changed.
In addition a button is added to the top of the target table alongside
the add/remove buttons.
This is a faster way of doing remove/add for a large quantity of
targets.
> Adds a move function for the target list

- tom_dataproducts/templatetags/dataproduct_extras.py
The query doesn't actually filter by target, so it does not reflect
recent photometry for the target displayed on the Target Detail page.
> Fix query for the "Recent Photometry" table

- tom_alerts/views.py
This was probably put in here for testing and not removed, but the
results from alert brokers should not be limited, but if they must be
limited, it should be documented somewhere on the template. I think it
should be fine to just return them all since the TOM has already
downloaded them all at this point.
> Do not artificially limit alert results

- tom_alerts/brokers/mars.py
- tom_alerts/tests/brokers/test_mars.py
- tom_dataproducts/templatetags/dataproduct_extras.py
This PR implements a few things:
1. Adds support for importing magnitude error from MARS lightcurves.
2. Adds support for importing non detections from MARS lightcurves.
3. Implements plotting both of the above on the photometry for target
plot.
4. Fixes photometry being saved under the wrong filter.
I hope you will consider mergint this, as by default the photometry plot
is missing quite a bit of useful data.
> Add mag error and nondetections to mars and plot

- tom_dataproducts/templatetags/dataproduct_extras.py
- tom_targets/static/tom_targets/css/main.css
This PR adds a few config options to the photometry plot, so that some
basic aesthetic parameters can be changed. Width, height, background
color, etc. Defaults should show no change.
I'm not sure the best place to document this. Any thoughts?
> Add a few configuration options to the photo plot

- tom_common/templates/tom_common/navbar_content.html
The text for dropdowns was hardcoded to black, which is not good if you
want to use an astronomer approved all dark mode theme.
Applying the correct classes and html removes the need for hardcoding
black, and I think I also fixed the intended behavior of the"acive"
class, which looks a lot better now.
> Fixes the CSS/HTML so navbar displays properly

- tom_targets/filters.py
This PR adds a django_fitlers.OrderingFilter to the filter form on the
target list page, allowing users to choose the order in which to display
targets in the table.
The SD Tom requires this because we frequently update our targets and
would like targets with recent updates to appear higher in the list.
> Adds an ordering option to the target list page

- tom_targets/templatetags/targets_extras.py
This PR adds a parameter to the `target_plan` inclusion tag which allows
the plot to render on page load with default parameters equal to the
next 24 hours and 2.5 airmass.
The default behvior or requiring the form to filled out and submitted
remains unchanged.
This doesn't seem to have much of an effect on page load time so it
might be better to make this behavior the default. The param can even be
preserved but setting it causes the plot NOT to render by default.
> Adds a param to the airmass plot to render on load

- tom_catalogs/harvesters/simbad.py
- tom_catalogs/tests/harvesters/test_simbad.py
Canary tests have been failing for 16 nights. While almost all of them are due to a bizarre unreproducible specutils error, the very first one was a SIMBAD query failure. The SIMBAD script service no longer returns data for Messier objects, so the change to HD289002 should resolve the issue.
The fact that the SIMBAD harvester module will no longer return Messier objects should be noted, but the new exception handling probably means that it's not a bug.
> Fixed simbad canary test, added exception handling to catalog search

- setup.py
`django-filter` has switched from semantic versioning to calendar versioning. While there's a Dependabot PR, it includes a version band of 2.4 < version < 22, which could cause issues if for some reason a version is mistakenly released in that wide band.
This PR should supercede #504 and #504 should be closed.
> Updated django-filter version for new CalVer

- tom_dataproducts/templates/tom_dataproducts/partials/reduceddatum_sparkline.html
- tom_dataproducts/templatetags/dataproduct_extras.py
Adds a templatetag to render a sparkine generated from the magnitude of
reduceddatums stored for a target. This is not rendered anywhere by
default in the toolkit for now but can be used by any TOM if desired.
> Adds reduceddatum_sparkline template tag

- tom_observations/templates/tom_observations/observationrecord_detail.html
- tom_observations/views.py
Resolves #451 by switching from the old `DataProduct.get_image_data` to the new `DataProduct.get_preview`. The new method correctly checks that the file is actually a FITS _image_ and not just any FITS file.
> fix thumbnail display on observation detail page

- tom_targets/templatetags/targets_extras.py
This is a minor fix to the sexagesimal coordinate formatting on the target detail page. The current specification of `05.3f` does not add leading zeros to the last field as required (it would need to be `06.3f` to count the decimal point in the string length). However, while I was here, I switched to the built-in Astropy formatting of coordinates, which is easier to understand.
I also corrected the spelling of sexagesimal in the docstring, but not in the function name, in case that would break things for users. If you wanted to, you could make an alias of this function with the correct spelling.
> fix sexagesimal coordinate formatting

- tom_observations/templatetags/observation_extras.py
- tom_observations/utils.py
Right now, the visibility chart on the observation form page shows the airmass for all available facilities. This quickly gets crowded, with all the LCO sites plus Gemini by default. Some of the sites (e.g., Chile) also overlap each other.
These changes restrict that chart to only plot the visibility for the facility for which you are requesting observations. The `observation_plan` function already had an argument `facility` that was not used (I assume this was the intention), which I just had to pipe through to `get_sidereal_visibility`. The default behavior of these functions has not been changed.
> display only relevant visibility on observation form

- tom_observations/facilities/lco.py
- tom_observations/facilities/soar.py
Right now the "facility status" tab on the target page lists every LCO site twice. This is because the `SOARFacility` inherits its `get_facility_status` method from `LCOFacility`, which gets the status of every LCO site from the scheduler. This fix just removes that inheritance so that each LCO site is only listed once (from `LCOFacility.get_facility_status`).
> remove SOARFacility.get_facility_status inheritance

- tom_targets/models.py
- tom_targets/tests/tests.py
If a user attempts to save a None type as an extra django will throw a database error
.`django.db.utils.IntegrityError: NOT NULL constraint failed: tom_targets_targetextra.value`
As brokers provide data on targets sometimes an element of the alert is a None that has not been cast to a string or otherwise process. If a user were to try to save the alert as a bunch of TargetExtras django would not allow the None to be put into the database. This fix checks the parameter to be saved in TargetExtra, if it is `None` type then it rewrites the value as the string `'None'`
> protect against none extra

- tom_alerts/models.py
- tom_dataproducts/models.py
This is to allow a record to be kept for each `ReducedDatum` about how it was shared, or where it came from.
> Add a table to the DB for storing the source/destination of shared data

- setup.py
We want our dependencies to be as permissive as possible and eliminate `==` requirements.
> Stretch dependencies and requirements

- tom_catalogs/harvesters/tns.py
The TNS now requires additional headers for access to its APIs. These were already implemented in the TNS Broker, but not yet in the TNS Harvester.
> update TNS harvester with new TNS API protocol

- setup.py
- tom_common/forms.py
> Fix django 4.2 incompatability

- docs/targets/target_matcher.rst
- tom_base/settings.py
- tom_targets/models.py
Some bugs in the docs needed fixing, and we shouldn't require a match manager in settings for users who have no need of one.
> Fix target match doc fix

- tom_alerts/brokers/tns.py
Can't use a DateTimeField since we are storing the parameters in a JSONField and datetimes are not json serializable. Just a string date makes more sense anyway since we pass it through to TNS and they can interpret it how they want.
> Fix the date field on the tns broker

- tom_setup/management/commands/tom_setup.py
This simply clarifies the the purpose of the confusing set-up question.
I think another solution would be to remove the question, set the default key in `settings.py` to sidereal, and edit the docs and add a comment to `settings.py` to let users know that they can set this value to "non-sidereal" if they want that to be the default form that comes up first when creating new targets.
> Clarify sidereal vs non-sidereal setup prompt

- tom_dataproducts/views.py
This pull request addresses two issues related to the deletion of `DataProduct` objects. The first issue was that the files were not being properly deleted, causing name collisions for newly added files. This is in context of when adding previous observational data by obs ID.
In the previous version, deleting a `DataProduct` was being ignored because:
```
DeleteView uses FormMixin to handle POST requests. 
As a consequence, any custom deletion logic in DataProductDeleteView.delete() handler 
should be moved to form_valid().
```
This problem was noticed when a random string was being appended to filenames, due to collisions caused by the delete() method being ignored, after being deleted and re-added. Django appends such a string to avoid filename collision when the file is not actually …
> Fix Issues with DataProduct Deletion in DeleteView 

- tom_alerts/brokers/alerce.py
This change removes the reliance on the `page` key being returned successfully from the broker. We rely entirely on our own pagination count.
This Key is returned `null` for all requests from [ALeRCE](https://api.alerce.online/ztf/v1).
> remove reliance on alerce page return

- tom_observations/facilities/lco.py
This PR removes the grating field for FLOYDS observations.
I also added a "None" Option, though this doesn't really matter since the grating is ignored for both FLOYDS and NRES, but I could see it being confusing for observers who don't know what to do for instruments like NRES/FLOYDS that cannot take a grating.
> remove grating for FLOYDS observations.

- .readthedocs.yml
We've been encountering this error on our recent documentation builds:
```Problem in your project's configuration. Invalid configuration option "build.os": build not found```
The new `build` section of the config file supplies the `build.os` configuration option that they're complaining about.
Here's where they explained the change: https://blog.readthedocs.com/migrate-configuration-v2/
> add the newly required build section to readthedocs config file

- tom_dataproducts/models.py
Because of this line in [tom_dataproducts/models.py]( https://github.com/TOMToolkit/tom_base/blob/bbdef40be15cc6cd9dab5db2b04c82c6c7692025/tom_dataproducts/models.py#L237) if your FITS file image dimensions are not 1:1 the thumbnail will always be regenerated. 
I've put in a check that one of the axes fits into the default size i.e.
```
if im.size != THUMBNAIL_DEFAULT_SIZE and im.size[0] not in THUMBNAIL_DEFAULT_SIZE:
```
Its not a perfect solution but I think its better than the current situation. I could imagine making the `THUMBNAIL_DEFAULT_SIZE` is list of defaults but that would  have a much bigger impact on the code base and not be backwards compatible.
> Thumbnails fail if your FITS file isn't square

- tom_observations/templates/tom_observations/partials/observation_list.html
- tom_observations/views.py
- tom_targets/templates/tom_targets/target_detail.html
- tom_targets/views.py
Resolves Issue #697.
1. Introduces URL parameter support for directly navigating to specific tabs in the target detail view (e.g., `/targets/1/?tab=observations`). Initial implementation is limited to two sections that our users found most impactful but could be applied anywhere the directs to the target detail view. This was written with vanilla javascript, removing the concern of Jquery conflicts. 
2. Augments `observation_list.html` to display observation IDs, improving user experience to trace data to what ID in the overview.
> Add ability to navaigate to specific tab in target view.

- tom_alerts/tests/tests.py
- tom_alerts/views.py
Currently when a single target is ingested from a broker, it redirects to the target update page. This is awkward and a request has been made by users to default this to the target list page to be the same as having multiple targets ingested.
> remove special behavior for single target creation

- tom_dataproducts/templates/tom_dataproducts/partials/query_forced_photometry.html
I don't have a ton of experience with the forced photometry stuff.
I just want to make sure this doesn't break anything major before implementing it.
This removes the `bootstrap_css` so it doesn't overwrite the regular CSS from `base.html`.
I also snuck in a message about how to configure forced photometry in case none were currently available.
> remove bootstrap_css load in forced photometry html

- tom_targets/templates/tom_targets/partials/target_unknown_statuses.html
This is a very small change that hides the yellow "observations with unknown status" warning at the top of every target page unless there is actually an observation request with unknown status. Currently, I find myself ignoring that message because it appears at the top of every page, so I hope this will make it more useful. This makes it match the behavior of the green "upcoming observations" message, which only appears if there are pending observations.
> only show unknown status warning if there are any

- docs/managing_data/customizing_data_processing.rst
- tom_dataproducts/models.py
- tom_dataproducts/tests/tests.py
This should allow a user to add a `DATA_PRODUCT_PATH` value to their `settings.py` allowing for them to override the default path creation method for Data Products.
> Add Override for data Product path so user can define whatever path they like

- tom_setup/templates/tom_setup/settings.tmpl
This PR updates the `DATETIME_FORMAT` setting to correct a bug that caused the wrong time to be displayed in our application.
Previously, the DATETIME_FORMAT was set as:
```python
DATETIME_FORMAT = 'Y-m-d H:m:s'
```
However, this format string incorrectly used `m` (month) in the place where `i` (minute) should have been used. 
The corrected format string is:
```python
DATETIME_FORMAT = 'Y-m-d H:i:s'
```
This should resolve #638. 🙂
> Fix Incorrect Time Format in `DATETIME_FORMAT` Setting

- tom_common/static/tom_common/css/main.css
There is a known issue that adds extra space to Bootstrap text areas in Firefox: https://github.com/twbs/bootstrap/issues/23295
This adds a workaround so that single-line text areas are the same height as char fields in all browsers. Example screenshots attached. Note the height of the first field.
> remove extra space from text areas in Firefox

- docs/api/tom_alerts/brokers.rst
- tom_alerts/brokers/antares.py
- tom_alerts/brokers/hermes.py
Just adds some basic Docstrings from Antares and Hermes Brokers.
These are a little misleading because they require the modules to be installed in Tom_base to generate the full docstrings.
This obviously isn't possible right now for TOM Antares, and isn't done right now for Tom_Hermes, so this just adds the stub version docstrings to the readthedocs that explain how to install the full version.
> add Broker Documentation

- tom_alerts/templates/tom_alerts/query_result.html
- tom_alerts/tests/tests.py
- tom_alerts/views.py
Hey TOM team! A few suggested changes:
**Select All Checkbox**: Implemented a checkbox for selecting all targets returned from an alert query. This enhancement provides a convenient way for users to quickly select all targets and create corresponding target entries. The state of the checkbox is dynamically updated based on user selections as well.
**HTTPError Handling**: Added user feedback for cases where the alert query results in a timeout (previously leading to a 404 error) or any HTTPError. Now, if a query takes too long to execute, the system informs the user about the timeout and proceeds without returning any alerts. 
Not implemented but what do you think about removing the separate "View" column in the query results table. Instead, we can combine the URL of the alert with the …
> Add "Select All" checkbox and functionality to alert query view.

- tom_common/apps.py
- tom_setup/templates/tom_setup/settings.tmpl
This PR introduces the ability for users to customize the `plotly` theme directly from `settings.py`. By default, the theme is set to `plotly_white`, maintaining the current default behavior. 
This change empowers users with more flexibility in customizing the appearance of their Plotly charts, aligning with their personal or organizational branding and styling preferences. In the future, this should be extended to allow users to provide their own templates.
> Enhancement: Extend settings to set default plotly theme.

- tom_alerts/tests/tests.py
- tom_alerts/views.py
- tom_targets/models.py
- tom_targets/static/tom_targets/target_import.csv
- tom_targets/templates/tom_targets/target_import.html
- tom_targets/tests/tests.py
- tom_targets/utils.py
- tom_targets/views.py
This PR is to allow users to be able to view, edit, and delete targets that they create.
It adds permissions by default to the current user for the new target.
It also updates the csv file example and import process to handle USER GROUP permissions for the ingested target.
> User Permissions for new targets & CSV fixes

- tom_common/tests.py
- tom_common/views.py
Hi TOMTeam,
This PR introduces key updates to the `CommentDeleteView` in TOMToolkit.
- **CommentDeleteView Update**: Modified the view to use `form_valid` instead of `delete` for handling DELETE requests, aligning with Django's updated practices. 
- **Bugfix**: Corrects where the user is redirected to on success, addressing #649 
- **Testing Enhancements**: Added a new test class `CommentDeleteViewTest` in `tom_common/tests.py`, covering various scenarios including redirection for not logged-in users, authorization checks for superusers and normal users, and ensuring proper deletion.
> Modify comment deletion view to use form_valid.

- tom_alerts/brokers/alerce.py
This is a pretty simple change to add "ZTF" as the Telescope to the value of the `reduced_datum` when LC data is found during the ALeRCE Broker query.
This is necessary to share Data with Hermes.
> add ztf as telescope

- tom_targets/serializers.py
This fixes a bug where users could not see their own targets when created through the API and serializer.
> add user permissions to serializer created targets.

- tom_dataproducts/processors/spectroscopy_processor.py
- tom_dataproducts/tests/tests.py
The data processor module now requires an identifier for the source of the data product; without this the upload of the default sample data product given with the TOM fails.  Hence this is an urgent fix. 
I have added this for spectrum data products, although I have used placeholder values for the FITS format.  Ideally this should be read from the spectrum header but we will need to document the format and provide a data sample for this.
> Added facility identifier to the output of the spectrum processor

- tom_targets/templates/tom_targets/partials/module_buttons.html
This is a minor fix to allow mouseover (title) text for custom buttons.
> quotes around button title text

- tom_targets/templatetags/targets_extras.py
This is a minor fix to avoid the deprecation warning for `get_moon` (see [here](https://docs.astropy.org/en/stable/api/astropy.coordinates.get_moon.html)) by replacing it with `get_body`.
> update get_moon to get_body

- tom_dataproducts/alertstreams/hermes.py
- tom_dataproducts/models.py
- tom_dataproducts/processors/panstarrs_processor.py
- tom_dataproducts/templates/tom_dataproducts/partials/photometry_datalist_for_target.html
- tom_dataproducts/templatetags/dataproduct_extras.py
- tom_dataproducts/tests/test_sharing.py
- tom_dataproducts/tests/tests.py
This resolves #790 by making the naming convention for uncertainties on magnitudes consistent as "error". This should be resolved more robustly according to #609, but in the mean time, this allows the photometry table on the target detail page to work.
> rename magnitude_error to error

- tom_dataproducts/alertstreams/hermes.py
- tom_dataproducts/templates/tom_dataproducts/partials/photometry_datalist_for_target.html
- tom_dataproducts/templatetags/dataproduct_extras.py
This adds some backwards compatibility for functions that previously relied on `magnitude_error` that have been now changed to use `error` instead.
> add magnitude_error compatability

- docs/introduction/faqs.rst
A user reported to me by private email that the links in the FAQ to other pages in our own docs were broken.  Looks like this is due to them not having been updated to the current URL formatting, so this is now done.
> Updated format of old-style links to other pages of documentation

- tom_targets/base_models.py
- tom_targets/tests/tests.py
This should fix the issue with full precision floats interacting with badly when run through a bunch of trig and being stored  as part of the returned queryset for the cone search match manager.
This also adds some tests enforcing proper behavior for out of bounds search values.
> Fix cone matcher

- docs/targets/target_fields.rst
- tom_base/settings.py
- tom_targets/management/commands/converttargetextras.py
This code will automatically overwrite default values with ones from TargetExtras, but will also allow a user to overwrite any value using the `--force`` flag.
>  add option to override defaults to converttargetextras

- tom_dataproducts/models.py
Right now, it's not possible to update an existing `ReducedDatum`, because its `validate_unique` method will always find *itself* as a duplicate.
> exclude identical object in ReducedDatum.validate_unique

- docs/targets/target_fields.rst
This is to help make sure users have the appropriate resources to create their extended target models.
> add django references to docs

- docs/managing_data/single_target_data_service.rst
- tom_dataproducts/single_target_data_service/panstarrs_service/panstarrs.py
- tom_dataproducts/single_target_data_service/panstarrs_service/panstarrs_api.py
- tom_dataproducts/tasks.py
If you follow the documentation for [integrating a single target data service](https://tom-toolkit.readthedocs.io/en/stable/managing_data/single_target_data_service.html) with a TOM, the name of the corresponding configuration dictionary in settings.py seems to have been changed.  This PR makes the code consistent with the docs, which use the more generalized data services terminology.
> Updated name of config for single target data services

- tom_setup/templates/tom_setup/settings.tmpl
The Lasair API token needs to be capitalized.
> make broker settings consistent with docs

- tom_observations/templates/tom_observations/observationrecord_detail.html
`cancel_observation` is already a valid facility method that has been established for LCO.
This PR just adds a cancel button to the observation record detail page if the status is pending.
> add cancel button on observation record detail page.

- tom_observations/views.py
When the `get_form_classes_for_display` method is called (as introduced by #1071), the user is not set in the facility instance. This is done a few lines later. 
This patch moves the call to `facility.set_user` up to before the call to `get_form_classes_for_display`.
> Set user in facility before calling the get_form_classes_for_display.

- docs/common/customsettings.rst
- docs/common/permissions.rst
- docs/introduction/faqs.rst
This is just meant to acknowledge the `AnonymousUser` and explain its purpose in the permissions section of the docs.
Let me know if you think this is sufficient and in the best location.
> update docs with a brief description of AnonymousUser

- docs/api/tom_observations/models.rst
- docs/api/tom_targets/groups.rst
- docs/introduction/manual_installation.rst
- docs/observing/index.rst
- docs/targets/index.rst
- docs/targets/target_fields.rst
- tom_observations/facilities/lco.py
- tom_observations/templates/tom_observations/observation_form.html
- tom_observations/views.py
This adds a variety of minor documentation changes.
> 767 new tom creation documentation

- .github/workflows/github-release.yml
- .github/workflows/pypi-release.yml
- .github/workflows/run-tests.yml
- poetry.lock
- pyproject.toml
- tom_alerts/tests/brokers/test_alerce.py
- tom_observations/tests/facilities/test_lco.py
- tom_observations/tests/facilities/test_ocs.py
- tom_observations/tests/test_api.py
- tom_observations/tests/tests.py
- tom_targets/tests/tests.py
This PR removes support for python 3.8 and adds support for python 3.12.
Many dependencies do not have python 3.13 support yet, so we will wait to implement that.
> 1055 python 312

- docs/conf.py
- docs/index.rst
- poetry.lock
- pyproject.toml
`sphinx-panels` has been replaced by [sphinx-design](https://sphinx-design.readthedocs.io/en/latest/get_started.html#panel-directive-replaced) 
We use this primarily to make 1 button on the intro page (but it could be useful for other fancy things throughout the docs if we ever wanted to make them nice.)
> update docs for 3.12

- docs/targets/target_fields.rst
- tom_common/templatetags/tom_common_extras.py
- tom_targets/templates/tom_targets/partials/target_data.html
This will be the same text that is on the update form.
> display target model help text as tooltip

- tom_common/templates/auth/partials/app_user_lists.html
- tom_common/templates/auth/user_list.html
- tom_common/templates/tom_common/partials/app_profiles.html
- tom_common/templates/tom_common/partials/include_app_partial.html
- tom_common/templates/tom_common/partials/include_profile_card.html
- tom_common/templatetags/user_extras.py
Apps can use the available integration point to add specific tables to the user_list page.
> add integration point to user list page

- tom_common/urls.py
This will allow apps to overwrite tom_base URL paths.
This allows for individual apps to serve their own pages in place of the default ones.
(this is necessary for `tom_registration` to handle pending user login feedback.)
> set up app url patterns to be ingested first

- tom_targets/filters.py
- tom_targets/templates/tom_targets/partials/aladin_skymap.html
- tom_targets/templates/tom_targets/target_list.html
- tom_targets/templatetags/targets_extras.py
- tom_targets/tests/tests.py
- tom_targets/urls.py
- tom_targets/views.py
Uses a dedicated JSON endpoint to load targets for the Aladin map, making it efficient enough that _all_ (well, up to 10k) targets that match a filter can be displayed on the map, instead of only the 25 in the current pagination page. This is much more intuitive and what I'd expect to see on the map.
The 10k number can be adjusted but at that point there's so many targets that it's not worth adding more as you won't really be able to see a difference.
This is important because with infinite scroll, it's not possible to keep what is displayed on the Aladin map consistent with the current "page". 
Fixes [#1187](https://github.com/TOMToolkit/tom_base/issues/1187)
https://github.com/user-attachments/assets/e7413d70-95bd-45b9-8cc7-e6aeb06cd706
> 1187 aladin skymap blocking load catalog per target

- tom_targets/forms.py
- tom_targets/templates/tom_targets/targetlist_form.html
- tom_targets/tests/tests.py
- tom_targets/urls.py
- tom_targets/views.py
This commit solves the issue where on the target list page, the target list dropdown for bulk operations shows all target lists on the TOM, not just the ones the user has access too.
Additionally, this commit adds the option to select groups for which a newly created target list belongs to, giving users of those groups access to it.
Fixes #1141
> Only show target lists user has access to

- tom_common/models.py
- tom_common/signals.py
refactors signal receiver out of models.py to signals.py consistent with Django docs recommendation. See
https://docs.djangoproject.com/en/5.1/topics/signals/
> move DRF create_auth_token signal receiver to signals

- tom_targets/base_models.py
- tom_targets/filters.py
This is a simplification for filters to use the existing match filter for fuzzy name matching.
This bug was introduced a while ago with a refactor, and got missed.
> use updated fuzzy_name match

- tom_catalogs/harvesters/mpc.py
- tom_catalogs/tests/harvesters/data/test_65803_mpc_orb.json
- tom_catalogs/tests/harvesters/test_mpc.py
This fixes the MPC Harvester for the changes in fields used to make the `target` name. Fixes #1244
> Fix for the MPC Harvester designation changes

- tom_base/settings.py
- tom_setup/templates/tom_setup/settings.tmpl
- tom_targets/base_models.py
- tom_targets/tests/tests.py
Configurable so that individual implementations don't need to explicitly set the permissions default everywhere a target is created.
> Add setting for default permissions on Target

- docs/customization/encrypted_model_fields.rst
- docs/customization/index.rst
- fixes #1242 
To create html previews locally for this branch:
1. pip install sphinx sphinx-rtd-theme sphinx-panels sphinx_copybutton recommonmark
2. cd tom_base/docs
3. make html
4. point your browser to file:///path/to/tom_base/docs/_build/html/index.html
(that's all in the DevOps runbook but provided here for convenience)
> Add documentation for encrypted fields
