TOMToolkit/tom_base

tom_catalogs/harvester.py, tom_catalogs/harvesters/mpc.py
Adds MPC as an available source for querying targets
Fixes https://github.com/TOMToolkit/tom_base/issues/40
=> App MPC harvester class

tom_observations/models.py
Astropy includes image scaling classes, interesting to try out.
=> Use astropy's zscale algorith for image scaling

tom_alerts/alerts.py, tom_alerts/brokers/lasair.py
Roy WIlliam's code for integrating the LASAIR alert broker
=> Initial code for LASAIR broker

tom_alerts/brokers/mars.py
Modified JD conversion to be timezone-aware to stop Django from complaining
=> Fixed crash resulting from non-detections from MARS not having magpsf

tom_observations/facilities/gemini.py
This add support for a new 'exptime' parameter in the Gemini API.
=> Add exposure time field to Gemini

tom_dataproducts/models.py, tom_dataproducts/utils.py
Don't assume files are stored on disk, utilize django's storage
framework. Necessary for S3/GAE/etc integration.
=> Use data agnostic method for reading files

tom_observations/facilities/gemini.py
Added field to GEM observation screen
=> Add option to skip guide star search

tom_alerts/brokers/mars.py
Add deeplearning real bogus field in MARS query
=>  add drb__gte field in mars.py

tom_targets/views.py
Note: This will need to be implemented for the observation page (feature/observation_plot)
=> Update number of targets with filter

tom_alerts/views.py
=> jsonified cached alert to correct issue with processing data

tom_targets/templates/tom_targets/partials/target_data.html
Seems like an easy win to hide the fields which are left empty.
=> Hide target fields with no data

tom_observations/facilities/lco.py
After making the required fields for non-sidereal targets depend on the scheme chosen (https://github.com/TOMToolkit/tom_base/pull/179), submitting LCO observations no longer work, since some of the fields submitted in the JSON payload are empty (e.g. 'epoch_of_perihelion' is submitted always, but it is only relevant to comets).
This patch fixes this by submitting only the fields relevant to the chosen scheme.
=> Only submit relevant fields for LCO observations of non-sidereal targets

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .travis.yml
It is useful to test Python 3.6 compatibility, e.g. #196
=> Add python 3.6 to .travis.yml

tom_alerts/brokers/tns.py, tom_setup/templates/tom_setup/settings.tmpl
I made a first attempt at an alert broker module to query the [Transient Name Server](https://wis-tns.weizmann.ac.il) by name, coordinates, and/or discovery date.
=> add TNS broker

tom_targets/forms.py
=> Adding formatting hints

tom_alerts/alerts.py, tom_alerts/brokers/antares.py
Not a PR per se, more of a "what did you have in mind", but here is the simplest possible iteration of an ANTARES stub. Not sure if you were thinking something more generic, or more sophisticated, but hoping this is at least a conversation starter for what your ideas are.
=> Very basic plugin stub

tom_catalogs/harvesters/tns.py, tom_setup/templates/tom_setup/settings.tmpl
A couple of changes in development introduced breaking changes for tom_setup. This corrects those, and proactively updates the access method to the TNS API key to be consistent.
=> Updated templates to fix tom_setup

tom_base/settings.py, tom_common/middleware.py, tom_common/mixins.py, tom_observations/views.py, tom_setup/templates/tom_setup/settings.tmpl, tom_targets/tests/tests.py, tom_targets/views.py
This pull request addresses https://github.com/TOMToolkit/tom_base/issues/230
=> Add a Raise403PermissionRequiredMixin for more informational 403s

setup.py, tom_alerts/brokers/alerce.py
Cheking the ALeRCE broker plugin it was a bit outdated in the class taxonomy and with some queries, so I added some new features:
- Uses an API request to get the latest taxonomy for each classifier.
- Added relative date in hours instead of a fixed date (useful for early SN discovery)
- Sort the results by number of detections or probabilities.
- Give a maximum amount of retrieved pages to have a faster response time. 
It was passing all the code styles rules, don't know if the travis tests are passing.
Cheers~
Camilo.
=> Minor changes on ALeRCE Broker 

tom_observations/facilities/lt.py, tom_setup/templates/tom_setup/settings.tmpl, tom_targets/templates/tom_targets/partials/moon_distance.html, tom_targets/templates/tom_targets/target_detail.html, tom_targets/templatetags/targets_extras.py, tom_targets/tests/tests.py
Adapted the plot from snex2 for lunar distance and added it to the TOM Toolkit. Also made the code less Ascension and more Blue Train.
=> Added Jamie's moon distance plot

tom_targets/tests/tests.py
Ara's branch feature/target_grouping includes a number of changes to the actual group manipulation functions that are wildly out of date. However, the changes to the tests are still very pertinent. I've simply made his changes to the tests in master and branched off, so that there won't be any residual effects to the existing functionality, which works at the moment.
=> Updating tests to reflect changes by Ara before his departure

releasenotes.md, tom_observations/widgets.py
=> Added handling for programmatic submission of photseq form

tom_targets/filters.py, tom_targets/utils.py
This factors out the cone search functionality from the TargetFilter
class. The function is useful in other areas, so it is helpful to be
able to access it.
=> Factors out cone search function

tom_dataproducts/management/commands/updatereduceddata.py
The updatereduceddatum management command was failing with a stack trace due to the select previously on line 34. This was also causing the "Update Broker Data" on the target list page to fail as a result.
This PR returns the command to a functioning state.
=> Prevent command from crashing due to bad sql select

docs/observing/strategies.rst
=> Fix formatting

tom_alerts/brokers/alerce.py, tom_alerts/tests/brokers/test_alerce.py
Implements ALeRCEBroker.process_reduced_data to enable creating
ReducedDatums from the ALeRCE broker API.
=> alerce: Implement process_reduced_data.

tom_alerts/brokers/lasair.py
resolves #579 
Catches the exception and passes the details into feedback for user.
=> Gracefully handle no LASAIR token in settings

tom_dataproducts/sharing.py, tom_observations/facilities/lco.py
The LCO facility information was not being passed to the OCS template forms
=> Fix a bug with initiating LCO template forms

tom_alerts/brokers/scout.py, tom_alerts/brokers/tns.py, tom_alerts/templates/tom_alerts/query_result.html, tom_alerts/views.py
Fixes a typo in the scout documentation link.
Explains Current state of SCOUT Broker
Adds support and error messages for unconfigured TNS Broker
=> Clarification and fixes for SCOUT and TNS Brokers

CONTRIBUTING.md
This is a draft of a "how to contribute" document for TOM Base.
=> Create draft CONTRIBUTING.md

tom_dataproducts/models.py
=> Reduced datum validate comments

docs/introduction/getting_started.rst, docs/introduction/manual_installation.rst
This should clarify the preferred method of installation and remove confusion for new users.
=> 891 getting started docs

docs/targets/target_fields.rst, tom_base/settings.py, tom_setup/templates/tom_setup/models.tmpl, tom_setup/templates/tom_setup/settings.tmpl, tom_targets/base_models.py, tom_targets/management/commands/converttargetextras.py
Add a management command to convert Target Extras into new Target Fields created for a UserDefinedTarget.
=> add management command

docs/targets/target_fields.rst, tom_targets/views.py
This is a fix for the TargetGroupings page when a custom Target Model is active.
=> 975 targetlists broken with custom user model

tom_dataproducts/templatetags/dataproduct_extras.py
Don't try to plot random strings.
=> only include phtometry for plot if actually numbers

tom_targets/views.py
We should refactor this view to be a general Target List form and differentiate the idea of "Target Groupings" or `TargetList` from the `TargetListView` and the "Target List Page"
=> Handle merge condition before checking target lists

tom_catalogs/apps.py, tom_catalogs/harvester.py, tom_dataservices/dataservices.py, tom_setup/templates/tom_setup/settings.tmpl
@phycodurus Can we have a discussion about how to best utilize this integration point with an eye for backwards compatability as well as how best to use this new BaseClass for DataServices?
Please see the [DataServices Refactor Doc](https://docs.google.com/document/d/1FNdsI247OXJBss9IyG9-8pwsboBIg1xRnvoWGktF-bo/edit?usp=sharing), and the [BaseDataServices Class Doc](https://docs.google.com/document/d/1xdqlvl8NZCY_HaH1XsIcjNz92YGfnyZuO3hmpAleXCw/edit?usp=sharing).
=> add integration point and BaseClass

tom_observations/api_views.py, tom_observations/facility.py, tom_observations/views.py
This is the update to the docs:
We could also add an example in the customizing a facility section, but it seems pretty specific to this use case.
=> add function to retrieve facility form classes for display

tom_targets/base_models.py, tom_targets/templates/tom_targets/partials/target_data.html
=> add constellation to Target detail page

tom_common/templates/tom_common/partials/confirm_user_delete.html, tom_common/templates/tom_common/partials/navbar_login.html, tom_common/templates/tom_common/partials/user_data.html, tom_common/templates/tom_common/user_profile.html, tom_common/templatetags/user_extras.py, tom_common/tests.py, tom_common/urls.py, tom_common/views.py
This creates a basic profile page including the ability to edit and delete your profile.
resolves #1103
=> 1102 create a user profile page

tom_common/apps.py, tom_common/signals.py
Somehow this code was accidentally removed before the release.
=> fix profile bug

tom_common/templates/tom_common/partials/navbar_login.html, tom_common/urls.py, tom_common/views.py
Prevents people from accessing other people's profiles.
=> move profile page from user detail view

poetry.lock, pyproject.toml, tom_catalogs/harvesters/simbad.py
Pin astroquery to[ this commit ](https://github.com/astropy/astroquery/commit/e2db773ac2c9aaf4e2d79bcd0961b9cbb22f166e)until a new release is made.
=> get bugfix for astroquery still in dev

docs/code/backgroundtasks.rst, tom_alerts/brokers/tns.py
Docs weren't building.
This just addresses some issues and cleans up a few things.
=> fix some docs things

tom_targets/templates/tom_targets/target_form.html
=> Use target form value for initial value for permissions
